project:
  type: website
  output-dir: docs

website:
  site-url: https://philip.leftwich.github.io/
  google-analytics: "G-9SHEWYCPZ9"




  navbar:
    title: "Philip Leftwich"

    left:
      - text: About
        href: about.qmd
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
      - text: Resources
        menu:
          - talks_workshops.qmd
          - posts.qmd
          - myresources.qmd
 
    right:
      - icon: github
        href: https://github.com/philip-leftwich
      - icon: twitter
        href: https://twitter.com/PhilipLeftwich
      - icon: linkedin
        href: https://www.linkedin.com/in/philip-leftwich-117052155/
      - icon: envelope
        href: mailto:p.leftwich@uea.ac.uk
  page-footer: 
    background: light
    right: This website is built with [Quarto](https://quarto.org/)


format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - theme.scss
    mainfont: Nunito
    toc: true
    include-in-header: 
    - file: "analytics.html"  


